(function () {
    'use strict'; var $testimonialSlider = $('.testimonialSlider'), $testimonialSlider02 = $('.testimonialSlider02'), $homeBannarSlider03 = $('.homeBannarSlider03'), $projectSliderPJT02 = $('.projectSliderPJT02'), $projectSliderPJT03 = $('.projectSliderPJT03'), $projectSliderPJT04 = $('.projectSliderPJT04'), $projecetFullWidthSlider = $('.projecetFullWidthSlider'), $relatedPostSliderFilter01 = $('.relatedPostSliderFilter01'), $product_carousel = $('.product_carousel'), $gallery_sliders = $('.gallery_sliders'), $serviceSlider = $('.serviceSlider'), $popup_video = $('.popup_video'); $('.cmMainmenu li.menu-item-haschildren > a').on('click', function (e) { e.preventDefault(); $(this).siblings('ul').slideToggle(); }); $('.menuToggler').on('click', function (e) { e.preventDefault(); $('.cmMainmenu').slideToggle(); $(this).toggleClass('active'); }); $(window).on('scroll', function () { var heights = $(window).height(); if ($(window).scrollTop() > heights) { $(".isSticky").addClass('fixedHeader animated slideInDown'); } else { $(".isSticky").removeClass('fixedHeader animated slideInDown'); } }); if ($('.slider01').length > 0) { var revapi2 = jQuery('#rev_slider_1').show().revolution({ delay: 6000, responsiveLevels: [1200, 1140, 778, 480], gridwidth: [1140, 920, 700, 380], jsFileLocation: "js/", sliderLayout: "auto", minHeight: '890', navigation: { keyboardNavigation: "off", keyboard_direction: "horizontal", mouseScrollNavigation: "off", onHoverStop: "off", arrows: { style: "custom", enable: true, hide_onmobile: false, hide_onleave: false, tmp: '', left: { h_align: "right", v_align: "bottom", h_offset: 90, v_offset: 0 }, right: { h_align: "right", v_align: "bottom", h_offset: 0, v_offset: 0 } }, bullets: { enable: true, hide_under: 1000, style: 'custom', tmp: '<span class="bl"></span><span class="blCount">{{param1}}</span>', direction: 'vertical', rtl: false, container: 'slider', h_align: 'left', v_align: 'center', h_offset: 120, v_offset: 0, space: -18, hide_onleave: false, hide_onmobile: true, hide_under: 1000, hide_over: 9999, hide_delay: 200, hide_delay_mobile: 1200 } }, parallax: { type: 'mouse+scroll', origo: 'slidercenter', speed: 400, levels: [5, 10, 15, 20, 25, 30, 35, 40, 45, 46, 47, 48, 49, 50, 51, 55], disable_onmobile: 'on' } }); }
    if ($('.slider02').length > 0) { var revapi2 = jQuery('#rev_slider_2').show().revolution({ delay: 6000, responsiveLevels: [1200, 1140, 778, 480], gridwidth: [1140, 920, 700, 380], jsFileLocation: "js/", sliderLayout: "auto", minHeight: '890', navigation: { keyboardNavigation: "off", keyboard_direction: "horizontal", mouseScrollNavigation: "off", onHoverStop: "off", arrows: { style: "custom", enable: false }, bullets: { enable: true, style: 'custom', tmp: '<span class="bl"></span><span class="blCount">{{param1}}</span>', direction: 'vertical', rtl: false, container: 'slider', h_align: 'right', v_align: 'bottom', h_offset: 110, v_offset: 122, space: -18, hide_onleave: false, hide_onmobile: false, hide_under: 0, hide_over: 9999, hide_delay: 200, hide_delay_mobile: 1200 } } }); }
    function tw_stretch() {
        var i = $(window).width(); $(".row .tw-stretch-element-inside-column").each(function () {
            var $this = $(this), row = $this.closest(".row"), cols = $this.closest('[class^="col-"]'), colsheight = $this.closest('[class^="col-"]').height(), rect = this.getBoundingClientRect(), l = row[0].getBoundingClientRect(), s = cols[0].getBoundingClientRect(), r = rect.left, d = i - rect.right, c = l.left + (parseFloat(row.css("padding-left")) || 0), u = i - l.right + (parseFloat(row.css("padding-right")) || 0), p = s.left, f = i - s.right, styles = { "margin-left": 0, "margin-right": 0 }; if (Math.round(c) === Math.round(p)) { var h = parseFloat($this.css("margin-left") || 0); styles["margin-left"] = h - r; }
            if (Math.round(u) === Math.round(f)) { var w = parseFloat($this.css("margin-right") || 0); styles["margin-right"] = w - d; }
            $this.css(styles);
        });
    }
    tw_stretch(); if ($homeBannarSlider03.length > 0) { var $homeBannarSlider03_obj = $homeBannarSlider03.owlCarousel({ margin: 92, autoplay: true, loop: true, nav: true, navText: ['<i class="heaven-snake_arrow_right"></i>', '<i class="heaven-snake_arrow_right"></i>'], dots: false, items: 3, center: true, responsiveClass: true, responsive: { 0: { center: true, items: 1 }, 768: { items: 2 }, 1200: { items: 3 } } }); }
    if ($serviceSlider.length > 0) { var $serviceSlider_obj = $serviceSlider.owlCarousel({ margin: 30, autoplay: true, loop: true, nav: false, dots: false, items: 2, responsiveClass: true, responsive: { 0: { items: 1 }, 768: { items: 2 }, 1200: { items: 2 } } }); }
    $('.counters').appear(); $(document.body).on('appear', '.counters', function (e, $affected) { $affected.each(function () { var $this = $(this); if (!$this.hasClass('appeared')) { var numbers = $this.attr('data-count'); var suffix = $this.attr('data-suffix'); jQuery({ Counter: 0 }).animate({ Counter: numbers }, { duration: 3000, easing: 'swing', step: function () { var num = Math.ceil(this.Counter).toString(); $this.html(num + '' + suffix); } }); $this.addClass('appeared'); } }); }); if ($(".shaff_grid").length > 0) { var $grid = $('.shaff_grid'); var Shuffle = window.Shuffle; var element = document.querySelector('.shaff_grid'); var sizer = element.querySelector('.shafSizer'); var shaff_inst = new Shuffle(element, { itemSelector: '.shaff_item', sizer: sizer }); $('.mashFilterUL li').on('click', function () { $('.mashFilterUL li').removeClass('active'); $(this).addClass('active'); var groupName = $(this).attr('data-group'); shaff_inst.filter(groupName); }); }
    if ($(".service_grid").length > 0) { var $grid = $('.service_grid'); var Shuffle = window.Shuffle; var element = document.querySelector('.service_grid'); var sizer = element.querySelector('.shafSizer'); var shaff_inst = new Shuffle(element, { itemSelector: '.shaff_item', sizer: sizer }); }
    if ($popup_video.length > 0) { $popup_video.lightcase({ transition: 'elastic', showSequenceInfo: false, slideshow: false, swipe: true, showTitle: false, showCaption: false, controls: true }); }
    if ($testimonialSlider.length > 0) { var $testimonialSlider_obj = $testimonialSlider.owlCarousel({ margin: 0, autoplay: true, loop: true, nav: false, dots: true, items: 1 }); }
    if ($testimonialSlider02.length > 0) { var $testimonialSlider02_obj = $testimonialSlider02.owlCarousel({ margin: 30, autoplay: true, loop: true, nav: false, dots: true, items: 3, center: true, responsiveClass: true, responsive: { 0: { items: 1 }, 768: { items: 2 }, 1200: { items: 3 } } }); }
    if ($('.projectSliderWrap').length > 0) { $('.projectSliderWrap .projectSliderPJT02').each(function () { var $thisSlider = $(this); $thisSlider.slick({ autoplay: true, loop: true, dots: false, infinite: true, speed: 300, slidesToShow: 4, arrows: false, variableWidth: true, responsive: [{ breakpoint: 1200, settings: { slidesToShow: 4 } }, { breakpoint: 768, settings: { slidesToShow: 3 } }, { breakpoint: 480, settings: { variableWidth: false, slidesToShow: 1 } }] }); }); }
    if ($projectSliderPJT03.length > 0) { var $projectSliderPJT03_obj = $projectSliderPJT03.owlCarousel({ margin: 30, autoplay: true, loop: true, nav: false, dots: false, items: 5, responsiveClass: true, responsive: { 0: { items: 1 }, 768: { items: 2 }, 992: { items: 3 }, 1200: { items: 4 }, 1600: { items: 5 } } }); $('.sliderFilterUL').on('click', 'li', function () { var $item = $(this); var filter = $item.data('owl-filter'); $('.sliderFilterUL li').removeClass('active'); $item.addClass('active'); $projectSliderPJT03_obj.owlcarousel2_filter(filter); }) }
    if ($projectSliderPJT04.length > 0) { var $projectSliderPJT04_obj = $projectSliderPJT04.owlCarousel({ margin: 30, autoplay: true, center: true, loop: true, nav: false, dots: true, items: 3, responsiveClass: true, items: 2.5, responsive: { 0: { items: 1 }, 768: { items: 2 }, 1200: { items: 2 } } }); $('.sliderFilterUL').on('click', 'li', function () { var $item = $(this); var filter = $item.data('owl-filter'); $('.sliderFilterUL li').removeClass('active'); $item.addClass('active'); $projectSliderPJT04_obj.owlcarousel2_filter(filter); }) }
    if ($projecetFullWidthSlider.length > 0) { var $projecetFullWidthSlider_obj = $projecetFullWidthSlider.owlCarousel({ margin: 0, autoplay: true, speed: 1200, center: true, loop: true, nav: true, navText: ['<i class="heaven-angel-left"></i>', '<i class="heaven-angel-right"></i>'], dots: false, items: 1 }); }
    if ($relatedPostSliderFilter01.length > 0) { var $relatedPostSliderFilter01_obj = $relatedPostSliderFilter01.owlCarousel({ margin: 30, autoplay: false, loop: true, nav: false, dots: false, items: 3, responsiveClass: true, responsive: { 0: { items: 1 }, 768: { items: 2 }, 992: { items: 3 }, 1200: { items: 3 } } }); $('.sliderFilterUL').on('click', 'li', function () { var $item = $(this); var filter = $item.data('owl-filter'); $('.sliderFilterUL li').removeClass('active'); $item.addClass('active'); $relatedPostSliderFilter01_obj.owlcarousel2_filter(filter); }) }
    if ($gallery_sliders.length > 0) { $gallery_sliders.lightSlider({ gallery: true, item: 1, thumbItem: 4, slideMargin: 0, speed: 700, pause: 5000, auto: true, loop: true, galleryMargin: 0, thumbMargin: 9, currentPagerPosition: 'left', onSliderLoad: function () { $gallery_sliders.removeClass('cS-hidden'); } }); }
    if ($product_carousel.length > 0) { var $product_carousel_obj = $product_carousel.owlCarousel({ autoplay: true, margin: 30, loop: true, nav: true, navText: ['<i class="heaven-angel-left"></i>', '<i class="heaven-angel-right"></i>'], dots: false, items: 3, responsiveClass: true, responsive: { 0: { items: 1 }, 768: { items: 2 }, 992: { items: 3 } } }); }
    if ($(".single_skill").length > 0) { $('.single_skill').appear(); $('.single_skill').on('appear', loadSkills); }
    var coun = true; function loadSkills() { $(".single_skill").each(function () { var datacount = $(this).attr("data-parcent"); $(".ss_child", this).animate({ 'width': datacount + '%' }, 2000); if (coun) { $(this).find('.ss_parent h4').each(function () { var $this = $(this); $({ Counter: 0 }).animate({ Counter: datacount }, { duration: 2000, easing: 'swing', step: function () { $this.text(Math.ceil(this.Counter) + '%'); } }); }); } }); coun = false; }
    $(document).on('ready', function () {
        $("#close-popup").on('click', function (e) { e.preventDefault(); $("body").removeClass("menu__open show-overlay-nav") })
        $(".hamburger").on("click", function () { $(this).toggleClass("is_active"), $("body").toggleClass("menu__open") }), $(document).keyup(function (e) { 27 === e.keyCode && $(".menu__open .hamburger").on('click') }), $("#open-overlay-nav").on("click", function () { $("body").toggleClass("show-overlay-nav") }), $(".dl-menu__wrap").dlmenu({ animationClasses: { classin: "dl-animate-in-3", classout: "dl-animate-out-3" } });
    }); $(window).on("load", function () { $(".dl-menuwrapper > ul").mCustomScrollbar({ setHeight: 300 }); }); var back = $("#backtotop"), body = $("body, html"); $(window).on('scroll', function () { if ($(window).scrollTop() > $(window).height()) { back.css({ bottom: '30px', opacity: '1', visibility: 'visible' }); } else { back.css({ bottom: '-30px', opacity: '0', visibility: 'hidden' }); } }); body.on("click", "#backtotop", function (e) { e.preventDefault(); body.animate({ scrollTop: 0 }, 800); return false; }); if ($(".qtyBtn").length > 0) {
        $(".btnMinus").on('click', function () {
            var vals = parseInt($(this).next(".carqty").val(), 10); if (vals > 1) { vals -= 1; $(this).next(".carqty").val(vals).trigger('change'); } else { $(this).next(".carqty").val(vals).trigger('change'); }
            return false;
        }); $(".btnPlus").on('click', function () { var vals = parseInt($(this).prev(".carqty").val(), 10); vals += 1; $(this).prev(".carqty").val(vals).trigger('change'); return false; });
    }
    $(window).on('load', function () { var preload = $('.preloader'); if (preload.length > 0) { preload.delay(800).fadeOut('slow'); } }); $('#contact_form').on('submit', function (e) {
        e.preventDefault(); var $this = $(this); $('button[type="submit"]', this).attr('disabled', 'disabled').val('Processing...'); var form_data = $this.serialize(); var required = 0; $(".required", this).each(function () {
            if ($(this).val() === '') { $(this).addClass('reqError'); required += 1; } else {
                if ($(this).hasClass('reqError')) {
                    $(this).removeClass('reqError'); if (required > 0) { required -= 1; }
                }
            }
        }); if (required === 0) { $.ajax({ type: 'POST', url: 'mail/mail.php', data: { form_data: form_data }, success: function (data) { $('button[type="submit"]', $this).removeAttr('disabled').val('Message'); $('.con_message', $this).fadeIn().html('<strong>Congratulations!</strong> Your query successfully sent to site admin.').removeClass('alert-warning').addClass('alert-success'); setTimeout(function () { $('.con_message', $this).fadeOut().html('').removeClass('alert-success alert-warning'); }, 5000); } }); } else { $('button[type="submit"]', $this).removeAttr('disabled').val('Message'); $('.con_message', $this).fadeIn().html('<strong>Opps!</strong> Error found. Please fix those and re submit.').removeClass('alert-success').addClass('alert-warning'); setTimeout(function () { $('.con_message', $this).fadeOut().html('').removeClass('alert-success alert-warning'); }, 5000); }
    }); $(".required").on('keyup', function () { $(this).removeClass('reqError'); });
    // Stats Counter   auto play count
    document.addEventListener("DOMContentLoaded", function() {
        setTimeout(function() {
          animateCounter('counter1', 2000);
          animateCounter('counter2', 1900);
          animateCounter('counter3', 500);
          animateCounter('counter4', 4);
        }, 1000);
      });
    
      function animateCounter(counterId, targetValue) {
        let counterElement = document.getElementById(counterId);
        let countElement = counterElement.querySelector('.count');
        let currentValue = 0;
    
        let interval = setInterval(function() {
          currentValue += 10; 
          if (currentValue >= targetValue) {
            currentValue = targetValue;
            clearInterval(interval);
          }
    
          countElement.textContent = currentValue;
        }, 50);
      }
})(jQuery)